spring.application.name=order-service
spring.mongodb.uri=mongodb://localhost:27017/OrderServiceDB
server.port=8086

cart.service.url=http://localhost:8084
product.service.url=http://localhost:8083
user.service.url=http://localhost:8085
